[package]
name = "base-server"
version = "0.0.0"
edition = "2024"

[dependencies]
axum.workspace = true
tracing.workspace = true
tokio.workspace = true
base-config.workspace = true
database.workspace = true
trace-log.workspace = true
common.workspace = true
middleware.workspace = true
